services:
  frontend:
    image: docker.io/aemadmin/newlevelhub-web-frontend:latest
    pull_policy: always
    container_name: nlh_frontend_prod
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - nlh_network

networks:
  nlh_network:
    external: true
    name: newlevelhub-backend_nlh_network
