FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_API_BASE_URL=/api/v1
ARG VITE_APP_NAME=NewLevelHub
ARG VITE_IDLE_SESSION_TIMEOUT_MINUTES=30
ARG VITE_IDLE_SESSION_WARNING_MINUTES=2
ARG VITE_ABSOLUTE_SESSION_TIMEOUT_MINUTES=480
ARG VITE_ABSOLUTE_SESSION_WARNING_MINUTES=2
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_APP_NAME=$VITE_APP_NAME
ENV VITE_IDLE_SESSION_TIMEOUT_MINUTES=$VITE_IDLE_SESSION_TIMEOUT_MINUTES
ENV VITE_IDLE_SESSION_WARNING_MINUTES=$VITE_IDLE_SESSION_WARNING_MINUTES
ENV VITE_ABSOLUTE_SESSION_TIMEOUT_MINUTES=$VITE_ABSOLUTE_SESSION_TIMEOUT_MINUTES
ENV VITE_ABSOLUTE_SESSION_WARNING_MINUTES=$VITE_ABSOLUTE_SESSION_WARNING_MINUTES

RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
