export const NOTIFICATION_TYPE_LABEL_KEYS: Record<string, string> = {
  booking_confirmed:        'notifications.types.booking_confirmed',
  booking_reminder:         'notifications.types.booking_reminder',
  booking_cancelled:        'notifications.types.booking_cancelled',
  booking_completed:        'notifications.types.booking_completed',
  task_assigned:            'notifications.types.task_assigned',
  task_moved:               'notifications.types.task_moved',
  task_comment:             'notifications.types.task_comment',
  task_deadline:            'notifications.types.task_deadline',
  task_deadline_overdue:    'notifications.types.task_deadline_overdue',
  guest_validated:          'notifications.types.guest_validated',
  guest_pass_expiring:      'notifications.types.guest_pass_expiring',
  service_request_update:   'notifications.types.service_request_update',
  announcement:             'notifications.types.announcement',
  announcement_building:    'notifications.types.announcement_building',
  announcement_company:     'notifications.types.announcement_company',
  invitation:               'notifications.types.invitation',
  leave_review:             'notifications.types.leave_review',
  leave_approved:           'notifications.types.leave_approved',
  leave_rejected:           'notifications.types.leave_rejected',
  system:                   'notifications.types.system',
};
