export const NOTIFICATION_TYPE_LABEL_KEYS: Record<string, string> = {
  booking_confirmed: 'common.notificationType.booking_confirmed',
  booking_reminder: 'common.notificationType.booking_reminder',
  booking_cancelled: 'common.notificationType.booking_cancelled',
  task_assigned: 'common.notificationType.task_assigned',
  task_moved: 'common.notificationType.task_moved',
  task_comment: 'common.notificationType.task_comment',
  task_deadline: 'common.notificationType.task_deadline',
  task_deadline_overdue: 'common.notificationType.task_deadline_overdue',
  guest_validated: 'common.notificationType.guest_validated',
  guest_pass_expiring: 'common.notificationType.guest_pass_expiring',
  service_request_update: 'common.notificationType.service_request_update',
  announcement: 'common.notificationType.announcement',
  announcement_building: 'common.notificationType.announcement_building',
  announcement_company: 'common.notificationType.announcement_company',
  invitation: 'common.notificationType.invitation',
  leave_review: 'common.notificationType.leave_review',
  leave_approved: 'common.notificationType.leave_approved',
  leave_rejected: 'common.notificationType.leave_rejected',
  system: 'common.notificationType.system',
};
