export const API = {
  auth: {
    login: '/auth/login/',
    register: '/auth/register/',
    registerInvite: '/auth/register/invite/',
    logout: '/auth/logout/',
    me: '/auth/me/',
    refreshToken: '/auth/token/refresh/',
    forgotPassword: '/auth/password/reset/',
    resetPassword: '/auth/password/reset/confirm/',
    changePassword: '/auth/password/change/',
    verifyEmail: '/auth/email/verify/',
    resendVerification: '/auth/email/resend/',
    roles: '/auth/roles/',
  },
  companies: {
    list: '/companies/',
    create: '/companies/',
    detail: (id: string) => `/companies/${id}/`,
    limits: (id: string) => `/companies/${id}/limits/`,
    deactivate: (id: string) => `/companies/${id}/deactivate/`,
    activate: (id: string) => `/companies/${id}/activate/`,
    delete: (id: string) => `/companies/${id}/?confirm=true`,
    members: (id: string) => `/companies/${id}/members/`,
    invitations: (id: string) => `/companies/${id}/invitations/`,
    invitationRevoke: (companyId: string, invitationId: string) =>
      `/companies/${companyId}/invitations/${invitationId}/revoke/`,
    invitationResend: (companyId: string, invitationId: string) =>
      `/companies/${companyId}/invitations/${invitationId}/resend/`,
    settings: (id: string) => `/companies/${id}/settings/`,
    memberActivity: (companyId: string, userId: string) =>
      `/companies/${companyId}/members/${userId}/activity/`,
    memberDeactivate: (companyId: string, userId: string) =>
      `/companies/${companyId}/members/${userId}/deactivate/`,
    memberActivate: (companyId: string, userId: string) =>
      `/companies/${companyId}/members/${userId}/activate/`,
    memberRemove: (companyId: string, userId: string, reassignTo?: string) =>
      `/companies/${companyId}/members/${userId}/${reassignTo ? `?reassign_to=${reassignTo}` : ''}`,
    onboardingStatus: (companyId: string) => `/companies/${companyId}/onboarding/status/`,
    onboardingSkip: (companyId: string) => `/companies/${companyId}/onboarding/skip/`,
  },
  resources: {
    list: '/resources/',
    create: '/resources/',
    detail: (id: string) => `/resources/${id}/`,
    availability: (id: string) => `/resources/${id}/availability/`,
  },
  bookings: {
    list: '/bookings/',
    create: '/bookings/',
    detail: (id: string) => `/bookings/${id}/`,
    my: '/bookings/my/',
    manage: '/bookings/manage/',
    resources: {
      list: '/bookings/resources/',
      create: '/bookings/resources/',
      detail: (id: string) => `/bookings/resources/${id}/`,
      schedule: (id: string) => `/bookings/resources/${id}/schedule/`,
      bulkCreate: '/bookings/resources/bulk-create/',
    },
    reservations: {
      list: '/bookings/reservations/',
      create: '/bookings/reservations/',
      detail: (id: string) => `/bookings/reservations/${id}/`,
      my: '/bookings/reservations/my/',
      cancel: (id: string) => `/bookings/reservations/${id}/cancel/`,
      adminCancel: (id: string) => `/bookings/reservations/${id}/admin-cancel/`,
      addParticipants: (id: string) => `/bookings/reservations/${id}/participants/`,
      removeParticipant: (id: string, userId: string) =>
        `/bookings/reservations/${id}/participants/${userId}/`,
    },
  },
  crm: {
    boards: '/crm/boards/',
    board: (id: string) => `/crm/boards/${id}/`,
    columns: (boardId: string) => `/crm/boards/${boardId}/columns/`,
    tasks: (boardId: string) => `/crm/boards/${boardId}/tasks/`,
    task: (boardId: string, taskId: string) => `/crm/boards/${boardId}/tasks/${taskId}/`,
    myTasks: '/crm/tasks/my/',
  },
  team: {
    directory: '/team/',
    member: (id: string) => `/team/${id}/`,
    manage: '/team/manage/',
    invites: '/team/invites/',
  },
  calendar: {
    events: '/calendar/events/',
  },
  passes: {
    list: '/access/passes/',
    create: '/access/passes/',
    detail: (id: string) => `/access/passes/${id}/`,
    validate: (code: string) => `/access/passes/validate/${code}/`,
  },
  accessLog: {
    list: '/access/log/',
    export: '/access/log/export/',
  },
  building: {
    floors: '/building/floors/',
    floor: (id: string) => `/building/floors/${id}/`,
    markers: (floorId: string) => `/building/floors/${floorId}/markers/`,
  },
  serviceRequests: {
    list: '/service-requests/',
    create: '/service-requests/',
    detail: (id: string) => `/service-requests/${id}/`,
  },
  announcements: {
    list: '/announcements/',
    create: '/announcements/',
    detail: (id: string) => `/announcements/${id}/`,
  },
  leave: {
    requests: '/leave/requests/',
    create: '/leave/requests/',
    detail: (id: string) => `/leave/requests/${id}/`,
  },
  files: {
    list: '/files/',
    upload: '/files/upload/',
    detail: (id: string) => `/files/${id}/`,
    folders: '/files/folders/',
    folder: (id: string) => `/files/folders/${id}/`,
  },
  notifications: {
    list: '/notifications/',
    unreadCount: '/notifications/unread-count/',
    markRead: (id: string) => `/notifications/${id}/read/`,
    markAllRead: '/notifications/read-all/',
    settings: '/notifications/settings/',
  },
  analytics: {
    overview: '/analytics/overview/',
    bookings: '/analytics/bookings/',
    resources: '/analytics/resources/',
    company: (id: string) => `/analytics/companies/${id}/`,
  },
  profile: {
    me: '/auth/me/',
    update: '/auth/me/update/',
    deleteAvatar: '/auth/me/avatar/',
  },
  users: {
    list: '/auth/users/',
    detail: (id: number) => `/auth/users/${id}/`,
    block: (id: number) => `/auth/users/${id}/block/`,
    unblock: (id: number) => `/auth/users/${id}/unblock/`,
    impersonate: (id: number) => `/auth/users/${id}/impersonate/`,
  },
} as const;
