export const API = {
  auth: {
    login: '/auth/login/',
    register: '/auth/register/',
    registerInvite: '/auth/register/invite/',
    logout: '/auth/logout/',
    me: '/auth/me/',
    refreshToken: '/auth/token/refresh/',
    forgotPassword: '/auth/password/reset/',
    resetPassword: '/auth/password/reset/confirm/',
    changePassword: '/auth/password/change/',
    verifyEmail: '/auth/email/verify/',
    resendVerification: '/auth/email/resend/',
    roles: '/auth/roles/',
  },
  companies: {
    list: '/companies/',
    create: '/companies/',
    detail: (id: string) => `/companies/${id}/`,
    limits: (id: string) => `/companies/${id}/limits/`,
    deactivate: (id: string) => `/companies/${id}/deactivate/`,
    activate: (id: string) => `/companies/${id}/activate/`,
    delete: (id: string) => `/companies/${id}/?confirm=true`,
    members: (id: string) => `/companies/${id}/members/`,
    invitations: (id: string) => `/companies/${id}/invitations/`,
    invitationRevoke: (companyId: string, invitationId: string) =>
      `/companies/${companyId}/invitations/${invitationId}/revoke/`,
    invitationResend: (companyId: string, invitationId: string) =>
      `/companies/${companyId}/invitations/${invitationId}/resend/`,
    settings: (id: string) => `/companies/${id}/settings/`,
    memberActivity: (companyId: string, userId: string) =>
      `/companies/${companyId}/members/${userId}/activity/`,
    directory: (companyId: string) => `/companies/${companyId}/directory/`,
    directoryProfile: (companyId: string, userId: string) =>
      `/companies/${companyId}/directory/${userId}/`,
    memberDeactivate: (companyId: string, userId: string) =>
      `/companies/${companyId}/members/${userId}/deactivate/`,
    memberActivate: (companyId: string, userId: string) =>
      `/companies/${companyId}/members/${userId}/activate/`,
    memberRemove: (companyId: string, userId: string, reassignTo?: string) =>
      `/companies/${companyId}/members/${userId}/${reassignTo ? `?reassign_to=${reassignTo}` : ''}`,
    onboardingStatus: (companyId: string) => `/companies/${companyId}/onboarding-status/`,
    onboardingSkip: (companyId: string) => `/companies/${companyId}/onboarding-status/skip/`,
    calendar: (companyId: string) => `/companies/${companyId}/calendar/`,
    calendarBusy: (companyId: string) => `/companies/${companyId}/calendar/busy/`,
  },
  resources: {
    list: '/resources/',
    create: '/resources/',
    detail: (id: string) => `/resources/${id}/`,
    availability: (id: string) => `/resources/${id}/availability/`,
  },
  bookings: {
    list: '/bookings/',
    create: '/bookings/',
    detail: (id: string) => `/bookings/${id}/`,
    my: '/bookings/my/',
    manage: '/bookings/manage/',
    resources: {
      list: '/bookings/resources/',
      create: '/bookings/resources/',
      detail: (id: string) => `/bookings/resources/${id}/`,
      schedule: (id: string) => `/bookings/resources/${id}/schedule/`,
      activate: (id: string) => `/bookings/resources/${id}/activate/`,
      deactivate: (id: string) => `/bookings/resources/${id}/deactivate/`,
      block: (id: string) => `/bookings/resources/${id}/block/`,
      blocks: (id: string) => `/bookings/resources/${id}/blocks/`,
      unblock: (id: string, blockId: string) => `/bookings/resources/${id}/blocks/${blockId}/`,
      uploadPhoto: (id: string) => `/bookings/resources/${id}/photos/`,
      deletePhoto: (id: string, photoId: string) => `/bookings/resources/${id}/photos/${photoId}/`,
      bulkCreate: '/bookings/resources/bulk-create/',
    },
    reservations: {
      list: '/bookings/reservations/',
      create: '/bookings/reservations/',
      detail: (id: string) => `/bookings/reservations/${id}/`,
      my: '/bookings/reservations/my/',
      cancel: (id: string) => `/bookings/reservations/${id}/cancel/`,
      adminCancel: (id: string) => `/bookings/reservations/${id}/admin-cancel/`,
      checkIn: (id: string) => `/bookings/reservations/${id}/check-in/`,
      addParticipants: (id: string) => `/bookings/reservations/${id}/participants/`,
      removeParticipant: (id: string, userId: string) =>
        `/bookings/reservations/${id}/participants/${userId}/`,
    },
    recurring: {
      list: '/bookings/recurring/',
      create: '/bookings/recurring/',
      detail: (id: string) => `/bookings/recurring/${id}/`,
    },
  },
  crm: {
    boards: '/crm/boards/',
    board: (id: string) => `/crm/boards/${id}/`,
    boardArchive: (id: string) => `/crm/boards/${id}/archive/`,
    boardUnarchive: (id: string) => `/crm/boards/${id}/unarchive/`,
    columns: (boardId: string) => `/crm/boards/${boardId}/columns/`,
    column: (boardId: string, columnId: number) => `/crm/boards/${boardId}/columns/${columnId}/`,
    columnsReorder: (boardId: string) => `/crm/boards/${boardId}/columns/reorder/`,
    tasks: (boardId: string) => `/crm/boards/${boardId}/tasks/`,
    task: (boardId: string, taskId: string) => `/crm/boards/${boardId}/tasks/${taskId}/`,
    myTasks: '/crm/tasks/my/',
    tasksList: '/crm/tasks/',
    taskDetail: (id: number) => `/crm/tasks/${id}/`,
    taskChecklists: (taskId: number) => `/crm/tasks/${taskId}/checklists/`,
    checklistDetail: (checklistId: number) => `/crm/checklists/${checklistId}/`,
    checklistItems: (checklistId: number) => `/crm/checklists/${checklistId}/items/`,
    checklistItemDetail: (itemId: number) => `/crm/items/${itemId}/`,
    taskMove: (id: number) => `/crm/tasks/${id}/move/`,
    taskArchive: (id: number) => `/crm/tasks/${id}/archive/`,
    taskUnarchive: (id: number) => `/crm/tasks/${id}/unarchive/`,
    taskComments: (taskId: number) => `/crm/tasks/${taskId}/comments/`,
    taskCommentDetail: (taskId: number, commentId: number) => `/crm/tasks/${taskId}/comments/${commentId}/`,
    taskHistory: (taskId: number) => `/crm/tasks/${taskId}/history/`,
    taskAttachments: (taskId: number) => `/crm/tasks/${taskId}/attachments/`,
    taskAttachmentDetail: (taskId: number, attachmentId: number) => `/crm/tasks/${taskId}/attachments/${attachmentId}/`,
    labels: '/crm/labels/',
    labelDetail: (id: number) => `/crm/labels/${id}/`,
  },
  team: {
    directory: '/team/',
    member: (id: string) => `/team/${id}/`,
    manage: '/team/manage/',
    invites: '/team/invites/',
  },
  passes: {
    list: '/access/passes/',
    create: '/access/passes/',
    detail: (id: string) => `/access/passes/${id}/`,
    revoke: (id: string) => `/access/passes/${id}/revoke/`,
    resend: (id: string) => `/access/passes/${id}/resend/`,
    validate: '/access/validate/',
  },
  accessLog: {
    list: '/access/logs/',
    export: '/access/logs/export/',
  },
  building: {
    floors: '/building/floors/',
    floor: (id: string) => `/building/floors/${id}/`,
    markers: (floorId: string) => `/building/floors/${floorId}/markers/`,
  },
  map: {
    floors: '/services/floors/',
    floorMap: (floorId: number | string) => `/services/floors/${floorId}/map/`,
    search: '/services/map-points/search/',
    mapPoints: {
      list: '/services/map-points/',
      create: '/services/map-points/',
      detail: (id: number) => `/services/map-points/${id}/`,
    },
  },
  serviceRequests: {
    list: '/services/requests/',
    create: '/services/requests/',
    floors: '/services/floors/',
    quickCleaning: '/services/requests/quick-cleaning/',
    detail: (id: string) => `/services/requests/${id}/`,
    updateStatus: (id: string) => `/services/requests/${id}/status/`,
    rate: (id: string) => `/services/requests/${id}/rate/`,
  },
  announcements: {
    list: '/services/announcements/',
    create: '/services/announcements/',
    detail: (id: string) => `/services/announcements/${id}/`,
    markRead: (id: string) => `/services/announcements/${id}/read/`,
  },
  leave: {
    requests: '/hr/leaves/',
    create: '/hr/leaves/',
    detail: (id: string) => `/hr/leaves/${id}/`,
    review: (id: string) => `/hr/leaves/${id}/review/`,
    balance: '/hr/leaves/balance/',
    balanceSet: '/hr/leaves/balance/set/',
    balanceTeam: '/hr/leaves/balance/team/',
  },
  onboarding: {
    progress: '/hr/onboarding/progress/',
    completeStep: (stepId: number) => `/hr/onboarding/progress/steps/${stepId}/complete/`,
    teamProgress: '/hr/onboarding/progress/team/',
    templates: '/hr/onboarding/templates/',
    template: (templateId: number) => `/hr/onboarding/templates/${templateId}/`,
    templateSetDefault: (templateId: number) => `/hr/onboarding/templates/${templateId}/set-default/`,
  },
  storage: {
    folders: '/storage/folders/',
    folder: (id: string) => `/storage/folders/${id}/`,
    files: '/storage/files/',
    file: (id: string) => `/storage/files/${id}/`,
    fileDownload: (id: string) => `/storage/files/${id}/download/`,
    fileMove: (id: string) => `/storage/files/${id}/move/`,
    shares: '/storage/shares/',
    share: (id: string) => `/storage/shares/${id}/`,
    fileShares: (id: string) => `/storage/files/${id}/shares/`,
    usage: '/storage/usage/',
  },
  files: {
    list: '/files/',
    upload: '/files/upload/',
    detail: (id: string) => `/files/${id}/`,
    folders: '/files/folders/',
    folder: (id: string) => `/files/folders/${id}/`,
  },
  notifications: {
    list: '/notifications/',
    unreadCount: '/notifications/unread-count/',
    markRead: (id: string) => `/notifications/${id}/read/`,
    markAllRead: '/notifications/read-all/',
    delete: (id: string) => `/notifications/${id}/`,
    preferences: '/notifications/preferences/',
    doNotDisturb: '/notifications/do-not-disturb/',
  },
  analytics: {
    superadmin: '/analytics/superadmin/',
    superadminExport: '/analytics/superadmin/export/',
    companyExport: '/analytics/company/export/',
    overview: '/analytics/overview/',
    bookings: '/analytics/bookings/',
    resources: '/analytics/resources/',
    companyDashboard: '/analytics/company/',
    company: (id: string) => `/analytics/companies/${id}/`,
  },
  profile: {
    me: '/auth/me/',
    update: '/auth/me/update/',
    deleteAvatar: '/auth/me/avatar/',
  },
  users: {
    list: '/auth/users/',
    detail: (id: number) => `/auth/users/${id}/`,
    block: (id: number) => `/auth/users/${id}/block/`,
    unblock: (id: number) => `/auth/users/${id}/unblock/`,
    impersonate: (id: number) => `/auth/users/${id}/impersonate/`,
  },
  dashboard: '/dashboard/',
} as const;
